name       : lftp
version    : 4.8.3
release    : 11
source     :
    - https://lftp.yar.ru/ftp/lftp-4.8.3.tar.xz : de7aee451afaa1aa391f7076b5f602922c2da0e05524a8d8fea413eda83cc78b
license    : GPL-3.0
component  : network.clients
summary    : Terminal based FTP Client
description: |
    LFTP is a sophisticated ftp/http client, and a file transfer program supporting a number of network protocols.
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %configure --with-openssl=/usr/bin/openssl \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
