name       : lftp
version    : 4.6.4
release    : 2
source     :
    - http://lftp.yar.ru/ftp/lftp-4.6.4.tar.xz : 1e7cb674c83ace48172263f86847ed04bb6ab2f24116b11a8505f70a15e8805c
license    : GPL-3.0+
summary    : Terminal based FTP Client
description: |
    LFTP is a sophisticated ftp/http client, and a file transfer program supporting a number of network protocols. 
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %configure --with-openssl=/usr/bin/openssl
build      : |
    %make
install    : |
    %make_install
    rm -f %installroot%/usr/lib64/*.a
