name       : lftp
version    : 4.8.1
release    : 8
source     :
    - https://lftp.yar.ru/ftp/lftp-4.8.1.tar.xz : e770daa5592ad21bd0b8a8915a0f4fdc2e15dec6c69e754a870ad9c18be57b27
license    : GPL-3.0
component  : network.clients
summary    : Terminal based FTP Client
description: |
    LFTP is a sophisticated ftp/http client, and a file transfer program supporting a number of network protocols.
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %configure --with-openssl=/usr/bin/openssl \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
