name       : lftp
version    : 4.7.5
release    : 4
source     :
    - ftp://ftp.st.ryukoku.ac.jp/pub/network/ftp/lftp/lftp-4.7.5.tar.xz : 53b5c5eba2e38b418bcf451776f2df596050dff4db90ab4ea73d872f8b1fd0d8
license    : GPL-3.0
component  : network.clients
summary    : Terminal based FTP Client
description: |
    LFTP is a sophisticated ftp/http client, and a file transfer program supporting a number of network protocols.
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %configure --with-openssl=/usr/bin/openssl
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
