name       : lftp
version    : 4.6.2
release    : 1
source     :
    - ftp://ftp.cs.tu-berlin.de/pub/net/ftp/lftp/lftp-4.6.2.tar.xz : 1e61d5c94b06c333309185e86cfce0729e45e3f69f7496c58d61093b135c8bb9
license    : GPL-3.0+
summary    : Terminal based FTP Client
description: |
    LFTP is a sophisticated ftp/http client, and a file transfer program supporting a number of network protocols. 
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %configure --with-openssl=/usr/bin/openssl
build      : |
    %make
install    : |
    %make_install
    rm -f %installroot%/usr/lib64/*.a
