name       : lftp
version    : 4.9.0
release    : 14
source     :
    - https://lftp.yar.ru/ftp/lftp-4.9.0.tar.xz : 0b3b659e1969a31827a25861c01ccf71ac6d3f20ee256bdf6999d653e031a24e
license    : GPL-3.0-or-later
component  : network.clients
summary    : Terminal based FTP Client
description: |
    LFTP is a sophisticated ftp/http client, and a file transfer program supporting a number of network protocols.
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %configure --with-openssl=/usr/bin/openssl \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
# Only with networking
#check      : |
#    %make check
