name       : lftp
version    : 4.7.7
release    : 6
source     :
    - https://ftp.st.ryukoku.ac.jp/pub/network/ftp/lftp/lftp-4.7.7.tar.xz : 4483df04502660dcc65a11cf09d530e31bea99483d69328c1c5cbaa41d6619b4
license    : GPL-3.0
component  : network.clients
summary    : Terminal based FTP Client
description: |
    LFTP is a sophisticated ftp/http client, and a file transfer program supporting a number of network protocols.
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %configure --with-openssl=/usr/bin/openssl
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
